# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gitUI.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindowGitUiI(object):
    def setupUi(self, MainWindowGitUiI):
        MainWindowGitUiI.setObjectName(_fromUtf8("MainWindowGitUiI"))
        MainWindowGitUiI.resize(487, 482)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindowGitUiI.sizePolicy().hasHeightForWidth())
        MainWindowGitUiI.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../rcs/github-logo-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindowGitUiI.setWindowIcon(icon)
        MainWindowGitUiI.setAutoFillBackground(False)
        self.centralwidget = QtGui.QWidget(MainWindowGitUiI)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.groupBoxRepoType = QtGui.QGroupBox(self.centralwidget)
        self.groupBoxRepoType.setGeometry(QtCore.QRect(10, 4, 181, 51))
        self.groupBoxRepoType.setObjectName(_fromUtf8("groupBoxRepoType"))
        self.radioButtonLocalTypeRepo = QtGui.QRadioButton(self.groupBoxRepoType)
        self.radioButtonLocalTypeRepo.setGeometry(QtCore.QRect(10, 20, 71, 16))
        self.radioButtonLocalTypeRepo.setChecked(True)
        self.radioButtonLocalTypeRepo.setObjectName(_fromUtf8("radioButtonLocalTypeRepo"))
        self.radioButtonGithubTypeRepo = QtGui.QRadioButton(self.groupBoxRepoType)
        self.radioButtonGithubTypeRepo.setGeometry(QtCore.QRect(80, 20, 81, 16))
        self.radioButtonGithubTypeRepo.setObjectName(_fromUtf8("radioButtonGithubTypeRepo"))
        self.groupBoxInitialBackup = QtGui.QGroupBox(self.centralwidget)
        self.groupBoxInitialBackup.setEnabled(True)
        self.groupBoxInitialBackup.setGeometry(QtCore.QRect(200, 5, 271, 51))
        self.groupBoxInitialBackup.setObjectName(_fromUtf8("groupBoxInitialBackup"))
        self.pushButtonBrowseBackup = QtGui.QPushButton(self.groupBoxInitialBackup)
        self.pushButtonBrowseBackup.setGeometry(QtCore.QRect(10, 20, 61, 23))
        self.pushButtonBrowseBackup.setObjectName(_fromUtf8("pushButtonBrowseBackup"))
        self.lineEditBackupDir = QtGui.QLineEdit(self.groupBoxInitialBackup)
        self.lineEditBackupDir.setGeometry(QtCore.QRect(80, 20, 181, 21))
        self.lineEditBackupDir.setObjectName(_fromUtf8("lineEditBackupDir"))
        self.groupBoxUserSetup = QtGui.QGroupBox(self.centralwidget)
        self.groupBoxUserSetup.setGeometry(QtCore.QRect(10, 99, 461, 131))
        self.groupBoxUserSetup.setObjectName(_fromUtf8("groupBoxUserSetup"))
        self.formLayoutWidget_2 = QtGui.QWidget(self.groupBoxUserSetup)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(10, 12, 441, 111))
        self.formLayoutWidget_2.setObjectName(_fromUtf8("formLayoutWidget_2"))
        self.formLayoutUserSetup = QtGui.QFormLayout(self.formLayoutWidget_2)
        self.formLayoutUserSetup.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayoutUserSetup.setObjectName(_fromUtf8("formLayoutUserSetup"))
        self.lineEditEmail = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.lineEditEmail.setText(_fromUtf8(""))
        self.lineEditEmail.setObjectName(_fromUtf8("lineEditEmail"))
        self.formLayoutUserSetup.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEditEmail)
        self.lineEditUserName = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.lineEditUserName.setEnabled(False)
        self.lineEditUserName.setAutoFillBackground(False)
        self.lineEditUserName.setInputMethodHints(QtCore.Qt.ImhHiddenText)
        self.lineEditUserName.setReadOnly(False)
        self.lineEditUserName.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.lineEditUserName.setObjectName(_fromUtf8("lineEditUserName"))
        self.formLayoutUserSetup.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEditUserName)
        self.labelClientID = QtGui.QLabel(self.formLayoutWidget_2)
        self.labelClientID.setEnabled(False)
        self.labelClientID.setObjectName(_fromUtf8("labelClientID"))
        self.formLayoutUserSetup.setWidget(2, QtGui.QFormLayout.LabelRole, self.labelClientID)
        self.lineEditClientId = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.lineEditClientId.setEnabled(False)
        self.lineEditClientId.setObjectName(_fromUtf8("lineEditClientId"))
        self.formLayoutUserSetup.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEditClientId)
        self.labelClientSecret = QtGui.QLabel(self.formLayoutWidget_2)
        self.labelClientSecret.setEnabled(False)
        self.labelClientSecret.setObjectName(_fromUtf8("labelClientSecret"))
        self.formLayoutUserSetup.setWidget(3, QtGui.QFormLayout.LabelRole, self.labelClientSecret)
        self.lineEditClientSecret = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.lineEditClientSecret.setEnabled(False)
        self.lineEditClientSecret.setObjectName(_fromUtf8("lineEditClientSecret"))
        self.formLayoutUserSetup.setWidget(3, QtGui.QFormLayout.FieldRole, self.lineEditClientSecret)
        self.labelEmail = QtGui.QLabel(self.formLayoutWidget_2)
        self.labelEmail.setObjectName(_fromUtf8("labelEmail"))
        self.formLayoutUserSetup.setWidget(0, QtGui.QFormLayout.LabelRole, self.labelEmail)
        self.labelUserName = QtGui.QLabel(self.formLayoutWidget_2)
        self.labelUserName.setEnabled(False)
        self.labelUserName.setObjectName(_fromUtf8("labelUserName"))
        self.formLayoutUserSetup.setWidget(1, QtGui.QFormLayout.LabelRole, self.labelUserName)
        self.groupBoxSetTrigger = QtGui.QGroupBox(self.centralwidget)
        self.groupBoxSetTrigger.setGeometry(QtCore.QRect(10, 236, 461, 131))
        self.groupBoxSetTrigger.setObjectName(_fromUtf8("groupBoxSetTrigger"))
        self.labelActivateAt = QtGui.QLabel(self.groupBoxSetTrigger)
        self.labelActivateAt.setGeometry(QtCore.QRect(10, 20, 71, 20))
        self.labelActivateAt.setObjectName(_fromUtf8("labelActivateAt"))
        self.timeEditSetTrig = QtGui.QTimeEdit(self.groupBoxSetTrigger)
        self.timeEditSetTrig.setGeometry(QtCore.QRect(90, 20, 91, 20))
        self.timeEditSetTrig.setObjectName(_fromUtf8("timeEditSetTrig"))
        self.labelRecurEveryWeekOn = QtGui.QLabel(self.groupBoxSetTrigger)
        self.labelRecurEveryWeekOn.setGeometry(QtCore.QRect(10, 40, 151, 21))
        self.labelRecurEveryWeekOn.setObjectName(_fromUtf8("labelRecurEveryWeekOn"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.groupBoxSetTrigger)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 60, 421, 31))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayoutSunTue = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayoutSunTue.setObjectName(_fromUtf8("horizontalLayoutSunTue"))
        self.checkBoxSunday = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.checkBoxSunday.setObjectName(_fromUtf8("checkBoxSunday"))
        self.horizontalLayoutSunTue.addWidget(self.checkBoxSunday)
        self.checkBoxMonday = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.checkBoxMonday.setChecked(True)
        self.checkBoxMonday.setObjectName(_fromUtf8("checkBoxMonday"))
        self.horizontalLayoutSunTue.addWidget(self.checkBoxMonday)
        self.checkBoxTuesday = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.checkBoxTuesday.setObjectName(_fromUtf8("checkBoxTuesday"))
        self.horizontalLayoutSunTue.addWidget(self.checkBoxTuesday)
        self.checkBoxWed = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.checkBoxWed.setObjectName(_fromUtf8("checkBoxWed"))
        self.horizontalLayoutSunTue.addWidget(self.checkBoxWed)
        self.horizontalLayoutWidget_2 = QtGui.QWidget(self.groupBoxSetTrigger)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 90, 421, 31))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayoutWedFri = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayoutWedFri.setObjectName(_fromUtf8("horizontalLayoutWedFri"))
        self.checkBoxThursday = QtGui.QCheckBox(self.horizontalLayoutWidget_2)
        self.checkBoxThursday.setObjectName(_fromUtf8("checkBoxThursday"))
        self.horizontalLayoutWedFri.addWidget(self.checkBoxThursday)
        self.checkBoxFriday = QtGui.QCheckBox(self.horizontalLayoutWidget_2)
        self.checkBoxFriday.setObjectName(_fromUtf8("checkBoxFriday"))
        self.horizontalLayoutWedFri.addWidget(self.checkBoxFriday)
        self.checkBoxSat = QtGui.QCheckBox(self.horizontalLayoutWidget_2)
        self.checkBoxSat.setObjectName(_fromUtf8("checkBoxSat"))
        self.horizontalLayoutWedFri.addWidget(self.checkBoxSat)
        self.horizontalLayoutWidget_4 = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(197, 384, 281, 41))
        self.horizontalLayoutWidget_4.setObjectName(_fromUtf8("horizontalLayoutWidget_4"))
        self.horizontalLayoutFinish = QtGui.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayoutFinish.setObjectName(_fromUtf8("horizontalLayoutFinish"))
        self.pushButtonManageRepo = QtGui.QPushButton(self.horizontalLayoutWidget_4)
        self.pushButtonManageRepo.setEnabled(False)
        self.pushButtonManageRepo.setObjectName(_fromUtf8("pushButtonManageRepo"))
        self.horizontalLayoutFinish.addWidget(self.pushButtonManageRepo)
        self.pushButtonOK = QtGui.QPushButton(self.horizontalLayoutWidget_4)
        self.pushButtonOK.setEnabled(False)
        self.pushButtonOK.setObjectName(_fromUtf8("pushButtonOK"))
        self.horizontalLayoutFinish.addWidget(self.pushButtonOK)
        self.pushButtonExit = QtGui.QPushButton(self.horizontalLayoutWidget_4)
        self.pushButtonExit.setObjectName(_fromUtf8("pushButtonExit"))
        self.horizontalLayoutFinish.addWidget(self.pushButtonExit)
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(11, 63, 461, 31))
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.labelDaysHistoryFront = QtGui.QLabel(self.groupBox)
        self.labelDaysHistoryFront.setGeometry(QtCore.QRect(10, 5, 151, 21))
        self.labelDaysHistoryFront.setObjectName(_fromUtf8("labelDaysHistoryFront"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(239, 9, 46, 13))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.spinBoxHistory = QtGui.QSpinBox(self.groupBox)
        self.spinBoxHistory.setGeometry(QtCore.QRect(180, 7, 42, 16))
        self.spinBoxHistory.setObjectName(_fromUtf8("spinBoxHistory"))
        MainWindowGitUiI.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindowGitUiI)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 487, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindowGitUiI.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindowGitUiI)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindowGitUiI.setStatusBar(self.statusbar)
        self.actionExit = QtGui.QAction(MainWindowGitUiI)
        self.actionExit.setStatusTip(_fromUtf8(""))
        self.actionExit.setWhatsThis(_fromUtf8(""))
        self.actionExit.setShortcutContext(QtCore.Qt.WidgetShortcut)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionManage_Repo = QtGui.QAction(MainWindowGitUiI)
        self.actionManage_Repo.setObjectName(_fromUtf8("actionManage_Repo"))
        self.actionManual = QtGui.QAction(MainWindowGitUiI)
        self.actionManual.setObjectName(_fromUtf8("actionManual"))
        self.actionAbout = QtGui.QAction(MainWindowGitUiI)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionManageRpo = QtGui.QAction(MainWindowGitUiI)
        self.actionManageRpo.setObjectName(_fromUtf8("actionManageRpo"))
        self.menuFile.addAction(self.actionManageRpo)
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionManual)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindowGitUiI)
        QtCore.QMetaObject.connectSlotsByName(MainWindowGitUiI)

    def retranslateUi(self, MainWindowGitUiI):
        MainWindowGitUiI.setWindowTitle(_translate("MainWindowGitUiI", "Git report tool: TemcoNepal", None))
        self.groupBoxRepoType.setTitle(_translate("MainWindowGitUiI", "Repository Type", None))
        self.radioButtonLocalTypeRepo.setText(_translate("MainWindowGitUiI", "Local", None))
        self.radioButtonGithubTypeRepo.setText(_translate("MainWindowGitUiI", "Github", None))
        self.groupBoxInitialBackup.setTitle(_translate("MainWindowGitUiI", "Initial backup directory", None))
        self.pushButtonBrowseBackup.setText(_translate("MainWindowGitUiI", "Browse", None))
        self.lineEditBackupDir.setPlaceholderText(_translate("MainWindowGitUiI", "Initial backup directory", None))
        self.groupBoxUserSetup.setTitle(_translate("MainWindowGitUiI", "Set User", None))
        self.lineEditEmail.setPlaceholderText(_translate("MainWindowGitUiI", "Git report will be sent to this email", None))
        self.lineEditUserName.setPlaceholderText(_translate("MainWindowGitUiI", "Enter git/github username", None))
        self.labelClientID.setText(_translate("MainWindowGitUiI", "Git Client Id", None))
        self.lineEditClientId.setPlaceholderText(_translate("MainWindowGitUiI", "Enter github client ID", None))
        self.labelClientSecret.setText(_translate("MainWindowGitUiI", "Git Client Secret", None))
        self.lineEditClientSecret.setPlaceholderText(_translate("MainWindowGitUiI", "Enter github client secret", None))
        self.labelEmail.setText(_translate("MainWindowGitUiI", "Recipient\'s Email", None))
        self.labelUserName.setText(_translate("MainWindowGitUiI", "Git Username", None))
        self.groupBoxSetTrigger.setTitle(_translate("MainWindowGitUiI", "Set Trigger", None))
        self.labelActivateAt.setText(_translate("MainWindowGitUiI", "Activate at", None))
        self.labelRecurEveryWeekOn.setText(_translate("MainWindowGitUiI", "Recur every week on:", None))
        self.checkBoxSunday.setText(_translate("MainWindowGitUiI", "Sunday", None))
        self.checkBoxMonday.setText(_translate("MainWindowGitUiI", "Monday", None))
        self.checkBoxTuesday.setText(_translate("MainWindowGitUiI", "Tuesday", None))
        self.checkBoxWed.setText(_translate("MainWindowGitUiI", "Wednesday", None))
        self.checkBoxThursday.setText(_translate("MainWindowGitUiI", "Thursday", None))
        self.checkBoxFriday.setText(_translate("MainWindowGitUiI", "Friday", None))
        self.checkBoxSat.setText(_translate("MainWindowGitUiI", "Saturday", None))
        self.pushButtonManageRepo.setText(_translate("MainWindowGitUiI", "Manage Repo", None))
        self.pushButtonOK.setText(_translate("MainWindowGitUiI", "OK", None))
        self.pushButtonExit.setText(_translate("MainWindowGitUiI", "Exit", None))
        self.labelDaysHistoryFront.setText(_translate("MainWindowGitUiI", "Include user history within last", None))
        self.label_2.setText(_translate("MainWindowGitUiI", "days.", None))
        self.menuFile.setTitle(_translate("MainWindowGitUiI", "File", None))
        self.menuHelp.setTitle(_translate("MainWindowGitUiI", "Help", None))
        self.actionExit.setText(_translate("MainWindowGitUiI", "Exit", None))
        self.actionManage_Repo.setText(_translate("MainWindowGitUiI", "View Inputs", None))
        self.actionManage_Repo.setShortcut(_translate("MainWindowGitUiI", "Ctrl+M", None))
        self.actionManual.setText(_translate("MainWindowGitUiI", "Manual", None))
        self.actionManual.setShortcut(_translate("MainWindowGitUiI", "Ctrl+F1", None))
        self.actionAbout.setText(_translate("MainWindowGitUiI", "About", None))
        self.actionAbout.setShortcut(_translate("MainWindowGitUiI", "Ctrl+I", None))
        self.actionManageRpo.setText(_translate("MainWindowGitUiI", "Manage Repo", None))
        self.actionManageRpo.setShortcut(_translate("MainWindowGitUiI", "Ctrl+M", None))

